FINGRID_DATASETS = {
    "281": {
        "dataset_id": "281",
        "dataset_code": "fcrd_down_hourly_procured_volume",
        "name": "FCR-D down procured volumes in the hourly market",
        "description": "FCR-D down hourly procured reserve volume in Finland.",
        "unit": "MW",
        "frequency": "1h",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_procured_volume",
        "source_url": "https://data.fingrid.fi/en/datasets/281",
        "api_path": "/datasets/281/data",
        "series_key": "fcrd_down_hourly_procured_volume",
        "default_backfill_start": "2022-01-01T00:00:00Z",
        "default_incremental_lookback_days": 30,
        "supported_aggregations": ["raw", "1h", "2h", "4h", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-D Down",
            "signal": "procured_volume",
            "market_layer": "hourly",
        },
    },
    "283": {
        "dataset_id": "283",
        "dataset_code": "fcrd_down_hourly_market_price",
        "name": "FCR-D down hourly market prices",
        "description": "FCR-D down hourly reserve-capacity market price in Finland.",
        "unit": "EUR/MW",
        "frequency": "1h",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_capacity_price",
        "source_url": "https://data.fingrid.fi/en/datasets/283",
        "api_path": "/datasets/283/data",
        "series_key": "fcrd_down_hourly_market_price",
        "default_backfill_start": "2021-04-01T00:00:00Z",
        "default_incremental_lookback_days": 30,
        "supported_aggregations": ["raw", "1h", "2h", "4h", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-D Down",
            "signal": "capacity_price",
            "market_layer": "hourly",
        },
    },
    "288": {
        "dataset_id": "288",
        "dataset_code": "fcrn_yearly_market_plan",
        "name": "FCR-N reserve plans in the yearly market",
        "description": "FCR-N yearly market reserve plans in Finland.",
        "unit": "MW",
        "frequency": "1y",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_yearly_plan",
        "source_url": "https://data.fingrid.fi/en/datasets/288",
        "api_path": "/datasets/288/data",
        "series_key": "fcrn_yearly_market_plan",
        "default_backfill_start": "2021-01-01T00:00:00Z",
        "default_incremental_lookback_days": 365,
        "supported_aggregations": ["raw", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-N",
            "signal": "yearly_plan",
            "market_layer": "yearly",
        },
    },
    "290": {
        "dataset_id": "290",
        "dataset_code": "fcrd_up_yearly_market_plan",
        "name": "FCR-D up reserve plans in the yearly market",
        "description": "FCR-D up yearly market reserve plans in Finland.",
        "unit": "MW",
        "frequency": "1y",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_yearly_plan",
        "source_url": "https://data.fingrid.fi/en/datasets/290",
        "api_path": "/datasets/290/data",
        "series_key": "fcrd_up_yearly_market_plan",
        "default_backfill_start": "2020-01-01T00:00:00Z",
        "default_incremental_lookback_days": 365,
        "supported_aggregations": ["raw", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-D Up",
            "signal": "yearly_plan",
            "market_layer": "yearly",
        },
    },
    "315": {
        "dataset_id": "315",
        "dataset_code": "fcrd_up_hourly_procured_volume",
        "name": "FCR-D up procured volumes in the hourly market",
        "description": "FCR-D up hourly procured reserve volume in Finland.",
        "unit": "MW",
        "frequency": "1h",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_procured_volume",
        "source_url": "https://data.fingrid.fi/en/datasets/315",
        "api_path": "/datasets/315/data",
        "series_key": "fcrd_up_hourly_procured_volume",
        "default_backfill_start": "2020-01-01T00:00:00Z",
        "default_incremental_lookback_days": 30,
        "supported_aggregations": ["raw", "1h", "2h", "4h", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-D Up",
            "signal": "procured_volume",
            "market_layer": "hourly",
        },
    },
    "316": {
        "dataset_id": "316",
        "dataset_code": "fcrn_hourly_procured_volume",
        "name": "FCR-N procured volumes in the hourly market",
        "description": "FCR-N hourly procured reserve volume in Finland.",
        "unit": "MW",
        "frequency": "1h",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_procured_volume",
        "source_url": "https://data.fingrid.fi/en/datasets/316",
        "api_path": "/datasets/316/data",
        "series_key": "fcrn_hourly_procured_volume",
        "default_backfill_start": "2020-01-01T00:00:00Z",
        "default_incremental_lookback_days": 30,
        "supported_aggregations": ["raw", "1h", "2h", "4h", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-N",
            "signal": "procured_volume",
            "market_layer": "hourly",
        },
    },
    "317": {
        "dataset_id": "317",
        "dataset_code": "fcrn_hourly_market_price",
        "name": "FCR-N hourly market prices",
        "description": "FCR-N hourly reserve-capacity market price in Finland.",
        "unit": "EUR/MW",
        "frequency": "1h",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_capacity_price",
        "source_url": "https://data.fingrid.fi/en/datasets/317",
        "api_path": "/datasets/317/data",
        "series_key": "fcrn_hourly_market_price",
        "default_backfill_start": "2020-01-01T00:00:00Z",
        "default_incremental_lookback_days": 30,
        "supported_aggregations": ["raw", "1h", "2h", "4h", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-N",
            "signal": "capacity_price",
            "market_layer": "hourly",
        },
    },
    "318": {
        "dataset_id": "318",
        "dataset_code": "fcrd_up_hourly_market_price",
        "name": "FCR-D up hourly market prices",
        "description": "FCR-D up hourly reserve-capacity market price in Finland.",
        "unit": "EUR/MW",
        "frequency": "1h",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_capacity_price",
        "source_url": "https://data.fingrid.fi/en/datasets/318",
        "api_path": "/datasets/318/data",
        "series_key": "fcrd_up_hourly_market_price",
        "default_backfill_start": "2021-01-01T00:00:00Z",
        "default_incremental_lookback_days": 30,
        "supported_aggregations": ["raw", "1h", "2h", "4h", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-D Up",
            "signal": "capacity_price",
            "market_layer": "hourly",
        },
    },
    "319": {
        "dataset_id": "319",
        "dataset_code": "imbalance_price",
        "name": "Imbalance price",
        "description": "Imbalance price in Finland.",
        "unit": "EUR/MWh",
        "frequency": "1h+",
        "timezone": "Europe/Helsinki",
        "value_kind": "imbalance_price",
        "source_url": "https://data.fingrid.fi/en/datasets/319",
        "api_path": "/datasets/319/data",
        "series_key": "imbalance_price",
        "default_backfill_start": "2022-01-01T00:00:00Z",
        "default_incremental_lookback_days": 30,
        "supported_aggregations": ["raw", "1h", "2h", "4h", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "Imbalance",
            "signal": "settlement_price",
            "market_layer": "balancing",
        },
    },
    "321": {
        "dataset_id": "321",
        "dataset_code": "fcrd_down_yearly_market_plan",
        "name": "FCR-D down reserve plans in the yearly market",
        "description": "FCR-D down yearly market reserve plans in Finland.",
        "unit": "MW",
        "frequency": "1y",
        "timezone": "Europe/Helsinki",
        "value_kind": "reserve_yearly_plan",
        "source_url": "https://data.fingrid.fi/en/datasets/321",
        "api_path": "/datasets/321/data",
        "series_key": "fcrd_down_yearly_market_plan",
        "default_backfill_start": "2014-01-01T00:00:00Z",
        "default_incremental_lookback_days": 365,
        "supported_aggregations": ["raw", "day", "week", "month"],
        "metadata_json": {
            "market": "Fingrid",
            "product": "FCR-D Down",
            "signal": "yearly_plan",
            "market_layer": "yearly",
        },
    },
}


def get_dataset_config(dataset_id: str) -> dict:
    if dataset_id not in FINGRID_DATASETS:
        raise KeyError(f"Unsupported Fingrid dataset: {dataset_id}")
    return dict(FINGRID_DATASETS[dataset_id])


def list_dataset_configs() -> list[dict]:
    return [dict(FINGRID_DATASETS[key]) for key in sorted(FINGRID_DATASETS)]
